"""Models for extracting molecular geometries from periodic structures."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Mapping


@dataclass(frozen=True)
class MoleculeExtractionConfig:
    """User-controlled tolerances for molecular extraction."""

    bond_tolerance_factor: float = 1.20
    fingerprint_tolerance_A: float = 0.05
    rmsd_tolerance_A: float = 0.15
    symprec_A: float = 0.05
    angle_tolerance_deg: float = 5.0
    vacuum_padding_A: float = 10.0
    allow_reflection_equivalence: bool = False

    def __post_init__(self) -> None:
        for name in (
            "bond_tolerance_factor",
            "fingerprint_tolerance_A",
            "rmsd_tolerance_A",
            "symprec_A",
            "vacuum_padding_A",
        ):
            if getattr(self, name) <= 0.0:
                raise ValueError(f"{name} must be positive.")
        if self.angle_tolerance_deg <= 0.0:
            raise ValueError("angle_tolerance_deg must be positive.")


@dataclass(frozen=True)
class MoleculeOccurrence:
    """One molecular fragment found in the input unit cell."""

    molecule_instance_id: str
    geometry_id: str
    formula: str
    source_atom_indices: tuple[int, ...]
    com_frac: tuple[float, float, float]
    com_cart_A: tuple[float, float, float]


@dataclass(frozen=True)
class GeometryType:
    """One unique internal molecular geometry."""

    geometry_id: str
    formula: str
    atom_count: int
    fingerprint: str
    occurrence_ids: tuple[str, ...]
    xyz_path: Path | None = None
    poscar_path: Path | None = None


@dataclass(frozen=True)
class SymmetryMapping:
    """One successful molecule mapping generated by a space-group operation."""

    source_instance_id: str
    target_instance_id: str
    operation_index: int
    rmsd_A: float


@dataclass(frozen=True)
class SymmetryUniqueMolecule:
    """One representative of a molecular orbit under crystal symmetry."""

    unique_molecule_id: str
    geometry_id: str
    representative_instance_id: str
    occurrence_ids: tuple[str, ...]
    orbit_size: int
    xyz_path: Path | None = None
    poscar_path: Path | None = None


@dataclass(frozen=True)
class ExtractionResult:
    """Result returned by the molecular extractor."""

    output_dir: Path
    geometries: tuple[GeometryType, ...]
    occurrences: tuple[MoleculeOccurrence, ...]
    symmetry_unique_molecules: tuple[SymmetryUniqueMolecule, ...]
    symmetry_mappings: tuple[SymmetryMapping, ...]
    summary: Mapping[str, object]
