"""API for extracting unique molecular-crystal n-mers and ORCA inputs."""

from __future__ import annotations

from collections import Counter, defaultdict, deque
import csv
from dataclasses import dataclass, replace
import hashlib
from itertools import combinations, product
import json
from pathlib import Path
from typing import Iterable, Mapping, Sequence

import numpy as np
from pymatgen.core import Molecule, Structure
from pymatgen.core.periodic_table import Element
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from scipy.spatial import KDTree

from ..structures import load_poscar, write_poscar
from .models import (
    ClusterOccurrence,
    ClusterType,
    GenerationResult,
    MoleculeInstance,
    MoleculeType,
    NMerConfig,
    OrcaConfig,
)


_DEFAULT_COVALENT_RADII = {
    "H": 0.31,
    "C": 0.76,
    "N": 0.71,
    "O": 0.66,
    "F": 0.57,
    "S": 1.05,
    "Cl": 1.02,
    "Br": 1.14,
    "I": 1.33,
}


@dataclass
class _BaseMolecule:
    source_atom_indices: tuple[int, ...]
    species: tuple[str, ...]
    fractional_coords: np.ndarray
    formula: str
    fingerprint: str


@dataclass
class _MoleculeData:
    instance_id: str
    type_id: str
    molecule: Molecule
    source_atom_indices: tuple[int, ...]
    translation: tuple[int, int, int]
    com_cart_A: np.ndarray
    is_central: bool


@dataclass
class _ClusterData:
    cluster_type_id: str
    order: int
    cutoff_A: float
    molecules: tuple[_MoleculeData, ...]
    fingerprint: str
    occurrences: list[tuple[str, tuple[str, ...]]]


class CrystalNMerGenerator:
    """Generate unique molecular-crystal n-mers from POSCAR or CIF.

    The generator uses periodic bonding only to identify molecules. Candidate
    n-mers are then selected in a padded, non-periodic supercell using the
    distance between molecular centers of mass. Ghost atoms are intentionally
    not generated by this API.
    """

    def __init__(
        self,
        input_path: str | Path,
        *,
        config: NMerConfig,
        orca: OrcaConfig | None = None,
        covalent_radii: Mapping[str, float] | None = None,
    ):
        self.input_path = Path(input_path)
        self.config = config
        self.orca = orca or OrcaConfig()
        self.covalent_radii = {
            **_DEFAULT_COVALENT_RADII,
            **({key: float(value) for key, value in covalent_radii.items()} if covalent_radii else {}),
        }

        self.structure: Structure | None = None
        self.supercell_structure: Structure | None = None
        self.supercell_repetitions: tuple[int, int, int] | None = None
        self._base_molecules: list[_BaseMolecule] = []
        self._molecules: list[_MoleculeData] = []
        self._molecule_types: dict[str, MoleculeType] = {}
        self._molecule_by_id: dict[str, _MoleculeData] = {}
        self._clusters: dict[int, list[_ClusterData]] = defaultdict(list)
        self._cluster_paths: dict[str, dict[str, Path | None]] = {}
        self._occurrences: list[ClusterOccurrence] = []
        self._candidate_counts: Counter[int] = Counter()
        self._neighbor_counts: Counter[int] = Counter()
        self._space_group_symbol = "Unknown"
        self._space_group_number: int | None = None
        self._symmetry_operations_count = 0
        self._analyzed = False
        self._batch_manifest: list[dict[str, object]] = []

    @classmethod
    def from_file(
        cls,
        input_path: str | Path,
        *,
        cutoffs: Mapping[int, float],
        supercell_padding_A: float = 5.0,
        bond_tolerance_factor: float = 1.20,
        fingerprint_tolerance_A: float = 0.05,
        rmsd_tolerance_A: float = 0.15,
        symprec_A: float = 0.05,
        angle_tolerance_deg: float = 5.0,
        max_neighbors: int = 1000,
        orca: OrcaConfig | None = None,
        covalent_radii: Mapping[str, float] | None = None,
    ) -> "CrystalNMerGenerator":
        """Construct a generator from compact keyword configuration."""

        return cls(
            input_path,
            config=NMerConfig(
                cutoffs=cutoffs,
                supercell_padding_A=supercell_padding_A,
                bond_tolerance_factor=bond_tolerance_factor,
                fingerprint_tolerance_A=fingerprint_tolerance_A,
                rmsd_tolerance_A=rmsd_tolerance_A,
                symprec_A=symprec_A,
                angle_tolerance_deg=angle_tolerance_deg,
                max_neighbors=max_neighbors,
            ),
            orca=orca,
            covalent_radii=covalent_radii,
        )

    @property
    def molecule_types(self) -> tuple[MoleculeType, ...]:
        return tuple(self._molecule_types.values())

    @property
    def molecule_instances(self) -> tuple[MoleculeInstance, ...]:
        return tuple(self._public_molecule_instance(item) for item in self._molecules)

    @property
    def cluster_types(self) -> tuple[ClusterType, ...]:
        return tuple(
            self._public_cluster_type(cluster)
            for order in sorted(self._clusters)
            for cluster in self._clusters[order]
        )

    @property
    def cluster_occurrences(self) -> tuple[ClusterOccurrence, ...]:
        return tuple(self._occurrences)

    def analyze(self) -> None:
        """Load input, build the padded supercell, and generate n-mers."""

        self._load_structure()
        self._read_symmetry_metadata()
        self._build_supercell()
        self._identify_base_molecules()
        self._build_molecule_instances()
        self._generate_clusters()
        self._analyzed = True

    def generate(
        self,
        output_dir: str | Path,
        *,
        modes: Iterable[str] = ("full_cluster", "mbe"),
        batch_size: int | None = 5,
    ) -> GenerationResult:
        """Analyze the structure and write CSV, XYZ, ORCA, and batch outputs."""

        if not self._analyzed:
            self.analyze()

        output_root = Path(output_dir)
        output_root.mkdir(parents=True, exist_ok=True)
        if isinstance(modes, str):
            normalized_modes = (modes,)
        else:
            normalized_modes = tuple(dict.fromkeys(modes))
        self._cluster_paths = {}
        allowed_modes = {"full_cluster", "mbe"}
        unknown = set(normalized_modes) - allowed_modes
        if unknown:
            raise ValueError(f"Unknown output mode(s): {sorted(unknown)}")
        if not normalized_modes:
            raise ValueError("At least one output mode is required.")
        if "mbe" in normalized_modes:
            required_orders = set(range(2, self.config.max_order + 1))
            missing_orders = sorted(required_orders - set(self.config.cutoffs))
            if missing_orders:
                raise ValueError(
                    "mbe mode requires cutoffs for every order from 2 through "
                    f"{self.config.max_order}; missing {missing_orders}."
                )
        if batch_size is not None and batch_size < 1:
            raise ValueError("batch_size must be positive or None.")

        self._write_supercell(output_root)
        self._write_molecule_outputs(output_root)
        self._write_cluster_outputs(output_root)
        manifest = self._write_orca_inputs(output_root, normalized_modes)
        batch_paths = self._write_batches(output_root, normalized_modes, batch_size)
        summary = self._summary_rows()
        self._write_reports(output_root, summary, manifest, self._batch_manifest)

        molecule_types = tuple(
            self._molecule_types[key] for key in sorted(self._molecule_types)
        )
        return GenerationResult(
            output_dir=output_root,
            molecule_types=molecule_types,
            molecule_instances=self.molecule_instances,
            cluster_types=self.cluster_types,
            cluster_occurrences=self.cluster_occurrences,
            summary=tuple(summary),
            calculation_manifest=tuple(manifest),
            batch_paths=tuple(batch_paths),
        )

    def _load_structure(self) -> None:
        if not self.input_path.exists():
            raise FileNotFoundError(self.input_path)
        lower_name = self.input_path.name.lower()
        if lower_name.endswith(".cif") or lower_name.endswith(".cif.gz"):
            self.structure = Structure.from_file(str(self.input_path))
        else:
            self.structure = load_poscar(self.input_path)
        if len(self.structure) == 0:
            raise ValueError("The input structure contains no atoms.")

    def _read_symmetry_metadata(self) -> None:
        if not self.config.use_symmetry_metadata or self.structure is None:
            return
        try:
            analyzer = SpacegroupAnalyzer(
                self.structure,
                symprec=self.config.symprec_A,
                angle_tolerance=self.config.angle_tolerance_deg,
            )
            self._space_group_symbol = analyzer.get_space_group_symbol()
            self._space_group_number = analyzer.get_space_group_number()
            self._symmetry_operations_count = len(analyzer.get_symmetry_operations())
        except Exception:
            self._space_group_symbol = "Unknown"
            self._space_group_number = None
            self._symmetry_operations_count = 0

    def _build_supercell(self) -> None:
        assert self.structure is not None
        matrix = np.asarray(self.structure.lattice.matrix, dtype=float)
        volume = abs(float(np.linalg.det(matrix)))
        heights = [
            volume / np.linalg.norm(np.cross(matrix[1], matrix[2])),
            volume / np.linalg.norm(np.cross(matrix[2], matrix[0])),
            volume / np.linalg.norm(np.cross(matrix[0], matrix[1])),
        ]
        target_half_width = max(self.config.cutoffs.values()) + self.config.supercell_padding_A
        repetitions = []
        for height in heights:
            repetition = max(1, int(np.ceil(2.0 * target_half_width / height)))
            if repetition % 2 == 0:
                repetition += 1
            repetitions.append(repetition)
        repetitions = tuple(repetitions)
        self.supercell_repetitions = repetitions

        supercell_matrix = matrix * np.asarray(repetitions, dtype=float)[:, None]
        species: list[object] = []
        fractional_coords: list[np.ndarray] = []
        for translation in product(
            range(repetitions[0]), range(repetitions[1]), range(repetitions[2])
        ):
            for site in self.structure.sites:
                species.append(site.specie)
                fractional_coords.append(
                    (np.asarray(site.frac_coords, dtype=float) + np.asarray(translation))
                    / np.asarray(repetitions, dtype=float)
                )
        self.supercell_structure = Structure(
            lattice=supercell_matrix,
            species=species,
            coords=fractional_coords,
            coords_are_cartesian=False,
        )

    def _covalent_radius(self, symbol: str) -> float:
        if symbol in self.covalent_radii:
            return self.covalent_radii[symbol]
        radius = Element(symbol).covalent_radius
        if radius is None:
            raise ValueError(f"No covalent radius is available for element {symbol}.")
        return float(radius)

    def _identify_base_molecules(self) -> None:
        assert self.structure is not None
        n_sites = len(self.structure)
        adjacency: dict[int, list[tuple[int, tuple[int, int, int]]]] = {
            index: [] for index in range(n_sites)
        }
        radii = [self._covalent_radius(site.specie.symbol) for site in self.structure.sites]
        search_radius = max(radii) * 2.0 * self.config.bond_tolerance_factor

        for index, site in enumerate(self.structure.sites):
            for neighbor in self.structure.get_neighbors(site, search_radius):
                other = int(neighbor.index)
                image = tuple(int(value) for value in neighbor.image)
                if other == index and image == (0, 0, 0):
                    continue
                cutoff = (radii[index] + radii[other]) * self.config.bond_tolerance_factor
                if float(neighbor.nn_distance) > cutoff:
                    continue
                adjacency[index].append((other, image))
                adjacency[other].append((index, tuple(-value for value in image)))

        visited: set[int] = set()
        components: list[tuple[int, ...]] = []
        component_offsets: list[dict[int, tuple[int, int, int]]] = []
        for root in range(n_sites):
            if root in visited:
                continue
            offsets = {root: (0, 0, 0)}
            queue: deque[int] = deque([root])
            visited.add(root)
            while queue:
                current = queue.popleft()
                for neighbor, image in adjacency[current]:
                    current_offset = np.asarray(offsets[current], dtype=int)
                    candidate = tuple(int(value) for value in current_offset + np.asarray(image))
                    if neighbor not in offsets:
                        offsets[neighbor] = candidate
                        visited.add(neighbor)
                        queue.append(neighbor)
                    elif offsets[neighbor] != candidate:
                        raise ValueError(
                            "The covalent graph is periodic/infinite. "
                            "This input does not contain finite molecular fragments."
                        )
            members = tuple(sorted(offsets))
            components.append(members)
            component_offsets.append(offsets)

        base_molecules: list[_BaseMolecule] = []
        for members, offsets in zip(components, component_offsets):
            species = tuple(self.structure[index].specie.symbol for index in members)
            fractional = []
            for index in members:
                fractional.append(
                    np.asarray(self.structure[index].frac_coords, dtype=float)
                    + np.asarray(offsets[index], dtype=float)
                )
            fractional_array = np.asarray(fractional, dtype=float)
            formula = Molecule(
                species,
                fractional_array @ self.structure.lattice.matrix,
            ).composition.reduced_formula
            fingerprint = self._molecule_fingerprint(
                species,
                fractional_array @ self.structure.lattice.matrix,
            )
            base_molecules.append(
                _BaseMolecule(
                    source_atom_indices=members,
                    species=species,
                    fractional_coords=fractional_array,
                    formula=formula,
                    fingerprint=fingerprint,
                )
            )

        formulas = {item.formula for item in base_molecules}
        if len(formulas) > 1:
            raise NotImplementedError(
                "Multiple molecular formulas in one structure are not implemented. "
                f"Found: {sorted(formulas)}"
            )
        # Same-formula molecules with different fingerprints are separate
        # molecule types, which supports distinct conformations.
        self._base_molecules = base_molecules

    def _build_molecule_instances(self) -> None:
        assert self.structure is not None
        assert self.supercell_repetitions is not None
        lattice_matrix = self.structure.lattice.matrix
        center_translation = tuple((value - 1) // 2 for value in self.supercell_repetitions)

        type_by_fingerprint: dict[str, str] = {}
        for base in self._base_molecules:
            if base.fingerprint not in type_by_fingerprint:
                type_by_fingerprint[base.fingerprint] = f"M{len(type_by_fingerprint) + 1:06d}"

        instances: list[_MoleculeData] = []
        for translation in product(
            range(self.supercell_repetitions[0]),
            range(self.supercell_repetitions[1]),
            range(self.supercell_repetitions[2]),
        ):
            for base in self._base_molecules:
                coordinates = (base.fractional_coords + np.asarray(translation)) @ lattice_matrix
                molecule = Molecule(base.species, coordinates)
                type_id = type_by_fingerprint[base.fingerprint]
                instance_id = f"I{len(instances) + 1:06d}"
                instances.append(
                    _MoleculeData(
                        instance_id=instance_id,
                        type_id=type_id,
                        molecule=molecule,
                        source_atom_indices=base.source_atom_indices,
                        translation=tuple(int(value) for value in translation),
                        com_cart_A=np.asarray(molecule.center_of_mass, dtype=float),
                        is_central=tuple(translation) == center_translation,
                    )
                )

        self._molecules = instances
        self._molecule_by_id = {item.instance_id: item for item in instances}
        representatives: dict[str, _MoleculeData] = {}
        for item in instances:
            representatives.setdefault(item.type_id, item)
        self._molecule_types = {}
        for type_id, item in sorted(representatives.items()):
            base = next(base for base in self._base_molecules if base.fingerprint == self._fingerprint_for_instance(item))
            self._molecule_types[type_id] = MoleculeType(
                molecule_type_id=type_id,
                formula=base.formula,
                atom_count=len(base.species),
                fingerprint=base.fingerprint,
                charge=self.orca.charge,
                multiplicity=self.orca.multiplicity,
            )

    def _fingerprint_for_instance(self, item: _MoleculeData) -> str:
        return self._molecule_fingerprint(
            tuple(site.specie.symbol for site in item.molecule.sites),
            item.molecule.cart_coords,
        )

    def _generate_clusters(self) -> None:
        central_instances = [item for item in self._molecules if item.is_central]
        if not central_instances:
            raise ValueError("No central molecular instances were found in the supercell.")
        com_coords = np.asarray([item.com_cart_A for item in self._molecules], dtype=float)
        tree = KDTree(com_coords)

        for order, cutoff in sorted(self.config.cutoffs.items()):
            for central in central_instances:
                central_index = self._molecules.index(central)
                neighbor_indices = tree.query_ball_point(central.com_cart_A, cutoff)
                neighbors = [
                    self._molecules[index]
                    for index in neighbor_indices
                    if index != central_index
                ]
                neighbors.sort(
                    key=lambda item: float(np.linalg.norm(item.com_cart_A - central.com_cart_A))
                )
                if len(neighbors) > self.config.max_neighbors:
                    neighbors = neighbors[: self.config.max_neighbors]
                self._neighbor_counts[order] += len(neighbors)
                if len(neighbors) < order - 1:
                    continue

                for selected in combinations(neighbors, order - 1):
                    self._candidate_counts[order] += 1
                    members = (central, *selected)
                    self._register_cluster(order, cutoff, members)

    def _register_cluster(
        self,
        order: int,
        cutoff: float,
        members: tuple[_MoleculeData, ...],
    ) -> None:
        fingerprint = self._cluster_fingerprint(members)
        for cluster in self._clusters[order]:
            if cluster.fingerprint != fingerprint:
                continue
            if self._clusters_match(cluster.molecules, members):
                occurrence_id = f"OCC{len(self._occurrences) + 1:06d}"
                member_ids = tuple(item.instance_id for item in members)
                cluster.occurrences.append((occurrence_id, member_ids))
                self._occurrences.append(
                    ClusterOccurrence(
                        occurrence_id=occurrence_id,
                        cluster_type_id=cluster.cluster_type_id,
                        central_instance_id=members[0].instance_id,
                        member_instance_ids=member_ids,
                    )
                )
                return

        cluster_id = f"N{order}_{len(self._clusters[order]) + 1:06d}"
        occurrence_id = f"OCC{len(self._occurrences) + 1:06d}"
        member_ids = tuple(item.instance_id for item in members)
        cluster = _ClusterData(
            cluster_type_id=cluster_id,
            order=order,
            cutoff_A=cutoff,
            molecules=members,
            fingerprint=fingerprint,
            occurrences=[(occurrence_id, member_ids)],
        )
        self._clusters[order].append(cluster)
        self._occurrences.append(
            ClusterOccurrence(
                occurrence_id=occurrence_id,
                cluster_type_id=cluster_id,
                central_instance_id=members[0].instance_id,
                member_instance_ids=member_ids,
            )
        )

    def _molecule_fingerprint(self, species: Sequence[str], coords: np.ndarray) -> str:
        centered = np.asarray(coords, dtype=float) - np.mean(coords, axis=0)
        entries = []
        tolerance = self.config.fingerprint_tolerance_A
        for i in range(len(species)):
            for j in range(i + 1, len(species)):
                pair = tuple(sorted((species[i], species[j])))
                entries.append((pair, int(round(float(np.linalg.norm(centered[i] - centered[j])) / tolerance))))
        payload = {"species": sorted(species), "distances": sorted(entries)}
        return hashlib.sha1(json.dumps(payload, sort_keys=True).encode("utf-8")).hexdigest()

    def _cluster_fingerprint(self, members: Sequence[_MoleculeData]) -> str:
        species: list[str] = []
        coords: list[np.ndarray] = []
        for item in members:
            species.extend(site.specie.symbol for site in item.molecule.sites)
            coords.extend(item.molecule.cart_coords - members[0].com_cart_A)
        centered = np.asarray(coords, dtype=float) - np.mean(coords, axis=0)
        tolerance = self.config.fingerprint_tolerance_A
        distances = []
        for i in range(len(species)):
            for j in range(i + 1, len(species)):
                pair = tuple(sorted((species[i], species[j])))
                distances.append(
                    (
                        pair,
                        int(round(float(np.linalg.norm(centered[i] - centered[j])) / tolerance)),
                    )
                )
        payload = {
            "member_type_ids": [
                *sorted(item.type_id for item in members),
            ],
            "species": sorted(species),
            "distances": sorted(distances),
        }
        return hashlib.sha1(json.dumps(payload, sort_keys=True).encode("utf-8")).hexdigest()

    def _clusters_match(
        self,
        first: Sequence[_MoleculeData],
        second: Sequence[_MoleculeData],
    ) -> bool:
        if len(first) != len(second):
            return False

        for molecule_mapping in self._molecule_mappings(first, second):
            ordered_second = [second[index] for index in molecule_mapping]
            atom_mapping_options = []
            for first_molecule, second_molecule in zip(first, ordered_second):
                options = self._atom_mappings(first_molecule.molecule, second_molecule.molecule)
                if not options:
                    break
                atom_mapping_options.append(options)
            else:
                for atom_mappings in product(*atom_mapping_options):
                    first_coords = np.vstack([
                        item.molecule.cart_coords - first[0].com_cart_A for item in first
                    ])
                    second_coords = np.vstack([
                        item.molecule.cart_coords[list(mapping)] - second[0].com_cart_A
                        for item, mapping in zip(ordered_second, atom_mappings)
                    ])
                    first_species = [
                        site.specie.symbol for item in first for site in item.molecule.sites
                    ]
                    second_species = [
                        item.molecule.species[mapping_index].symbol
                        for item, mapping in zip(ordered_second, atom_mappings)
                        for mapping_index in mapping
                    ]
                    if first_species != second_species:
                        continue
                    if self._kabsch_rmsd(first_coords, second_coords) <= self.config.rmsd_tolerance_A:
                        return True
        return False

    def _molecule_mappings(
        self,
        first: Sequence[_MoleculeData],
        second: Sequence[_MoleculeData],
    ) -> list[tuple[int, ...]]:
        """Map cluster molecules using type and center-of-mass distances."""

        if len(first) != len(second):
            return []
        if Counter(item.type_id for item in first) != Counter(item.type_id for item in second):
            return []
        if len(first) == 1:
            return [(0,)]
        tolerance = max(self.config.fingerprint_tolerance_A * 2.0, self.config.rmsd_tolerance_A)
        first_distances = self._com_distance_matrix(first)
        second_distances = self._com_distance_matrix(second)
        order = sorted(
            range(len(first)),
            key=lambda index: (
                first[index].type_id,
                tuple(round(value / tolerance) for value in first_distances[index]),
            ),
        )
        mappings: list[tuple[int, ...]] = []
        mapping: dict[int, int] = {}
        used: set[int] = set()

        def visit(position: int) -> None:
            if position == len(order):
                mappings.append(tuple(mapping[index] for index in range(len(first))))
                return
            first_index = order[position]
            for second_index in range(len(second)):
                if second_index in used:
                    continue
                if first[first_index].type_id != second[second_index].type_id:
                    continue
                compatible = True
                for mapped_first, mapped_second in mapping.items():
                    if abs(
                        first_distances[first_index, mapped_first]
                        - second_distances[second_index, mapped_second]
                    ) > tolerance:
                        compatible = False
                        break
                if not compatible:
                    continue
                mapping[first_index] = second_index
                used.add(second_index)
                visit(position + 1)
                used.remove(second_index)
                del mapping[first_index]

        visit(0)
        return mappings

    @staticmethod
    def _com_distance_matrix(molecules: Sequence[_MoleculeData]) -> np.ndarray:
        coords = np.asarray([item.com_cart_A for item in molecules], dtype=float)
        differences = coords[:, None, :] - coords[None, :, :]
        return np.linalg.norm(differences, axis=2)

    def _atom_mappings(self, first: Molecule, second: Molecule) -> list[tuple[int, ...]]:
        """Find species-preserving mappings between molecular geometries."""

        first_species = [site.specie.symbol for site in first.sites]
        second_species = [site.specie.symbol for site in second.sites]
        if sorted(first_species) != sorted(second_species):
            return []
        if len(first_species) == 1:
            return [(0,)]

        first_coords = np.asarray(first.cart_coords, dtype=float)
        second_coords = np.asarray(second.cart_coords, dtype=float)
        first_distances = np.linalg.norm(
            first_coords[:, None, :] - first_coords[None, :, :], axis=2
        )
        second_distances = np.linalg.norm(
            second_coords[:, None, :] - second_coords[None, :, :], axis=2
        )
        tolerance = max(self.config.fingerprint_tolerance_A * 2.0, self.config.rmsd_tolerance_A)
        order = sorted(
            range(len(first_species)),
            key=lambda index: (
                first_species[index],
                tuple(round(value / tolerance) for value in first_distances[index]),
            ),
        )
        mappings: list[tuple[int, ...]] = []
        mapping: dict[int, int] = {}
        used: set[int] = set()
        max_mappings = 256

        def visit(position: int) -> None:
            if len(mappings) >= max_mappings:
                return
            if position == len(order):
                mappings.append(tuple(mapping[index] for index in range(len(first_species))))
                return
            first_index = order[position]
            candidates = [
                index
                for index, symbol in enumerate(second_species)
                if symbol == first_species[first_index] and index not in used
            ]
            for second_index in candidates:
                if all(
                    abs(first_distances[first_index, mapped_first] - second_distances[second_index, mapped_second])
                    <= tolerance
                    for mapped_first, mapped_second in mapping.items()
                ):
                    mapping[first_index] = second_index
                    used.add(second_index)
                    visit(position + 1)
                    used.remove(second_index)
                    del mapping[first_index]
                    if len(mappings) >= max_mappings:
                        return

        visit(0)
        return mappings

    def _kabsch_rmsd(self, first: np.ndarray, second: np.ndarray) -> float:
        first_centered = first - np.mean(first, axis=0)
        second_centered = second - np.mean(second, axis=0)
        covariance = first_centered.T @ second_centered
        u, _, vt = np.linalg.svd(covariance)
        rotation = vt.T @ u.T
        if not self.config.allow_reflection_equivalence and np.linalg.det(rotation) < 0:
            vt[-1, :] *= -1.0
            rotation = vt.T @ u.T
        aligned = first_centered @ rotation
        return float(np.sqrt(np.mean(np.sum((aligned - second_centered) ** 2, axis=1))))

    def _write_supercell(self, output_root: Path) -> None:
        assert self.supercell_structure is not None
        path = output_root / "supercell" / "supercell.vasp"
        path.parent.mkdir(parents=True, exist_ok=True)
        write_poscar(self.supercell_structure, path)

    def _write_molecule_outputs(self, output_root: Path) -> None:
        xyz_dir = output_root / "molecules" / "xyz"
        xyz_dir.mkdir(parents=True, exist_ok=True)
        for type_id, item in sorted(self._representative_molecules().items()):
            path = xyz_dir / f"{type_id}.xyz"
            self._write_xyz(path, (item.molecule,), f"{type_id} {item.molecule.composition.reduced_formula}")
            self._molecule_types[type_id] = replace(self._molecule_types[type_id], xyz_path=path)

    def _write_cluster_outputs(self, output_root: Path) -> None:
        for order, clusters in sorted(self._clusters.items()):
            directory = output_root / "clusters" / f"n{order}"
            directory.mkdir(parents=True, exist_ok=True)
            for cluster in clusters:
                path = directory / f"{cluster.cluster_type_id}.xyz"
                self._write_xyz(path, tuple(item.molecule for item in cluster.molecules), cluster.cluster_type_id)
                cluster_type = self._public_cluster_type(cluster)
                updated = replace(cluster_type, xyz_path=path)
                self._replace_cluster_public_record(cluster, updated)

    def _write_orca_inputs(
        self,
        output_root: Path,
        modes: Sequence[str],
    ) -> list[dict[str, object]]:
        manifest: list[dict[str, object]] = []
        if "full_cluster" in modes:
            for order, clusters in sorted(self._clusters.items()):
                for cluster in clusters:
                    path = output_root / "calculations" / "full_cluster" / f"n{order}" / f"{cluster.cluster_type_id}.inp"
                    self._write_orca(path, cluster.cluster_type_id, [item.molecule for item in cluster.molecules])
                    self._cluster_paths.setdefault(cluster.cluster_type_id, {})["full_inp"] = path
                    manifest.append(
                        self._manifest_row("full_cluster", "nmer", cluster.cluster_type_id, order, path)
                    )
        if "mbe" in modes:
            for type_id, item in sorted(self._representative_molecules().items()):
                path = output_root / "calculations" / "mbe" / "monomers" / f"{type_id}.inp"
                self._write_orca(path, type_id, [item.molecule])
                manifest.append(self._manifest_row("mbe", "monomer", type_id, 1, path))
            for order, clusters in sorted(self._clusters.items()):
                for cluster in clusters:
                    path = output_root / "calculations" / "mbe" / f"n{order}" / f"{cluster.cluster_type_id}.inp"
                    self._write_orca(path, cluster.cluster_type_id, [item.molecule for item in cluster.molecules])
                    self._cluster_paths.setdefault(cluster.cluster_type_id, {})["mbe_inp"] = path
                    manifest.append(
                        self._manifest_row("mbe", "nmer", cluster.cluster_type_id, order, path)
                    )
        return manifest

    def _write_orca(self, path: Path, job_id: str, molecules: Sequence[Molecule]) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "$new_job",
            self.orca.method_line,
            f"%maxcore {self.orca.maxcore}",
            f"%pal nprocs {self.orca.nprocs}",
            "end",
            f'%id "{job_id}"',
            f"* xyz {self.orca.charge} {self.orca.multiplicity}",
        ]
        center = np.asarray(molecules[0].center_of_mass, dtype=float)
        for molecule in molecules:
            for site in molecule.sites:
                coords = np.asarray(site.coords, dtype=float) - center
                lines.append(
                    f"{site.specie.symbol} {coords[0]:12.6f} {coords[1]:12.6f} {coords[2]:12.6f}"
                )
        lines.append("*")
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    def _write_batches(
        self,
        output_root: Path,
        modes: Sequence[str],
        batch_size: int | None,
    ) -> list[Path]:
        self._batch_manifest = []
        if batch_size is None:
            return []
        result: list[Path] = []
        for mode in modes:
            source_root = output_root / "calculations" / mode
            if not source_root.exists():
                continue
            for group in sorted(path for path in source_root.iterdir() if path.is_dir()):
                files = sorted(group.glob("*.inp"))
                for start in range(0, len(files), batch_size):
                    batch_files = files[start : start + batch_size]
                    batch_path = output_root / "batches" / mode / group.name / f"batch_{start // batch_size + 1:03d}.inp"
                    batch_path.parent.mkdir(parents=True, exist_ok=True)
                    content = "\n\n".join(path.read_text(encoding="utf-8").rstrip() for path in batch_files)
                    batch_path.write_text(content + "\n", encoding="utf-8")
                    result.append(batch_path)
                    self._batch_manifest.append(
                        {
                            "mode": mode,
                            "group": group.name,
                            "batch_path": str(batch_path),
                            "input_count": len(batch_files),
                            "input_ids": "|".join(path.stem for path in batch_files),
                        }
                    )
        return result

    def _write_reports(
        self,
        output_root: Path,
        summary: Sequence[dict[str, object]],
        manifest: Sequence[dict[str, object]],
        batch_manifest: Sequence[dict[str, object]],
    ) -> None:
        reports = output_root / "statistics"
        reports.mkdir(parents=True, exist_ok=True)
        self._write_csv(reports / "molecule_types.csv", [
            {
                "molecule_type_id": item.molecule_type_id,
                "formula": item.formula,
                "atom_count": item.atom_count,
                "fingerprint": item.fingerprint,
                "xyz_path": self._relative_path(item.xyz_path, output_root),
                "charge": item.charge,
                "multiplicity": item.multiplicity,
            }
            for item in self.molecule_types
        ])
        self._write_csv(reports / "molecule_instances.csv", [
            {
                "molecule_instance_id": item.molecule_instance_id,
                "molecule_type_id": item.molecule_type_id,
                "source_atom_indices": "|".join(str(value) for value in item.source_atom_indices),
                "translation_a": item.translation[0],
                "translation_b": item.translation[1],
                "translation_c": item.translation[2],
                "com_x": item.com_cart_A[0],
                "com_y": item.com_cart_A[1],
                "com_z": item.com_cart_A[2],
                "is_central": item.is_central,
            }
            for item in self.molecule_instances
        ])
        self._write_csv(reports / "cluster_types.csv", [
            {
                "cluster_type_id": item.cluster_type_id,
                "order": item.order,
                "central_instance_id": item.central_instance_id,
                "member_instance_ids": "|".join(item.member_instance_ids),
                "member_type_ids": "|".join(item.member_type_ids),
                "multiplicity": item.multiplicity,
                "cutoff_A": item.cutoff_A,
                "fingerprint": item.fingerprint,
                "xyz_path": self._relative_path(item.xyz_path, output_root),
                "inp_path": self._relative_path(item.inp_path, output_root),
                "full_inp_path": self._relative_path(item.full_inp_path, output_root),
                "mbe_inp_path": self._relative_path(item.mbe_inp_path, output_root),
            }
            for item in self.cluster_types
        ])
        self._write_csv(reports / "cluster_members.csv", self._cluster_member_rows())
        self._write_csv(reports / "cluster_occurrences.csv", [
            {
                "occurrence_id": item.occurrence_id,
                "cluster_type_id": item.cluster_type_id,
                "central_instance_id": item.central_instance_id,
                "member_instance_ids": "|".join(item.member_instance_ids),
            }
            for item in self._occurrences
        ])
        self._write_csv(reports / "cluster_summary.csv", summary)
        self._write_csv(reports / "calculation_manifest.csv", manifest)
        self._write_csv(reports / "batch_manifest.csv", batch_manifest)

    def _summary_rows(self) -> list[dict[str, object]]:
        rows = []
        for order, cutoff in sorted(self.config.cutoffs.items()):
            clusters = self._clusters.get(order, [])
            rows.append(
                {
                    "order": order,
                    "cutoff_A": cutoff,
                    "neighbors_count": self._neighbor_counts[order],
                    "candidate_count": self._candidate_counts[order],
                    "unique_clusters": len(clusters),
                    "total_occurrences": sum(len(item.occurrences) for item in clusters),
                    "calculation_count": len(clusters),
                    "space_group": self._space_group_symbol,
                    "space_group_number": self._space_group_number,
                    "symmetry_operations": self._symmetry_operations_count,
                    "symmetry_method": "geometric_rmsd",
                }
            )
        return rows

    def _cluster_member_rows(self) -> list[dict[str, object]]:
        rows = []
        for cluster in self.cluster_types:
            for index, (instance_id, type_id) in enumerate(
                zip(cluster.member_instance_ids, cluster.member_type_ids)
            ):
                item = self._molecule_by_id[instance_id]
                distance = float(np.linalg.norm(item.com_cart_A - self._molecule_by_id[cluster.central_instance_id].com_cart_A))
                rows.append(
                    {
                        "cluster_type_id": cluster.cluster_type_id,
                        "member_index": index,
                        "molecule_instance_id": instance_id,
                        "molecule_type_id": type_id,
                        "is_central": index == 0,
                        "distance_to_central_A": distance,
                    }
                )
        return rows

    def _manifest_row(
        self,
        mode: str,
        object_type: str,
        object_id: str,
        order: int,
        path: Path,
    ) -> dict[str, object]:
        return {
            "calculation_id": f"CALC_{mode}_{object_id}",
            "mode": mode,
            "object_type": object_type,
            "object_id": object_id,
            "order": order,
            "input_path": str(path),
            "status": "prepared",
            "energy": None,
        }

    def _representative_molecules(self) -> dict[str, _MoleculeData]:
        representatives: dict[str, _MoleculeData] = {}
        for item in self._molecules:
            representatives.setdefault(item.type_id, item)
        return representatives

    def _public_molecule_instance(self, item: _MoleculeData) -> MoleculeInstance:
        return MoleculeInstance(
            molecule_instance_id=item.instance_id,
            molecule_type_id=item.type_id,
            source_atom_indices=item.source_atom_indices,
            translation=item.translation,
            com_cart_A=tuple(float(value) for value in item.com_cart_A),
            is_central=item.is_central,
        )

    def _public_cluster_type(self, cluster: _ClusterData) -> ClusterType:
        representative = cluster.occurrences[0][1]
        paths = self._cluster_paths.get(cluster.cluster_type_id, {})
        xyz_path = paths.get("xyz")
        full_inp_path = paths.get("full_inp")
        mbe_inp_path = paths.get("mbe_inp")
        return ClusterType(
            cluster_type_id=cluster.cluster_type_id,
            order=cluster.order,
            central_instance_id=representative[0],
            member_instance_ids=representative,
            member_type_ids=tuple(item.type_id for item in cluster.molecules),
            multiplicity=len(cluster.occurrences),
            cutoff_A=cluster.cutoff_A,
            fingerprint=cluster.fingerprint,
            xyz_path=xyz_path,
            inp_path=mbe_inp_path or full_inp_path,
            full_inp_path=full_inp_path,
            mbe_inp_path=mbe_inp_path,
        )

    def _replace_cluster_public_record(self, cluster: _ClusterData, updated: ClusterType) -> None:
        paths = self._cluster_paths.setdefault(cluster.cluster_type_id, {})
        paths["xyz"] = updated.xyz_path
        if updated.full_inp_path is not None:
            paths["full_inp"] = updated.full_inp_path
        if updated.mbe_inp_path is not None:
            paths["mbe_inp"] = updated.mbe_inp_path

    def _relative_path(self, path: Path | None, root: Path) -> str:
        if path is None:
            return ""
        try:
            return str(path.relative_to(root))
        except ValueError:
            return str(path)

    def _write_xyz(
        self,
        path: Path,
        molecules: Sequence[Molecule],
        comment: str,
    ) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        center = np.asarray(molecules[0].center_of_mass, dtype=float)
        atoms = []
        for molecule in molecules:
            for site in molecule.sites:
                coords = np.asarray(site.coords, dtype=float) - center
                atoms.append((site.specie.symbol, coords))
        lines = [str(len(atoms)), comment]
        lines.extend(
            f"{symbol} {coords[0]:.8f} {coords[1]:.8f} {coords[2]:.8f}"
            for symbol, coords in atoms
        )
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    @staticmethod
    def _write_csv(path: Path, rows: Sequence[dict[str, object]]) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        if not rows:
            path.write_text("\n", encoding="utf-8")
            return
        fields: list[str] = []
        for row in rows:
            for key in row:
                if key not in fields:
                    fields.append(key)
        with path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=fields)
            writer.writeheader()
            writer.writerows(rows)
