"""Lightweight POSCAR/CONTCAR reader and writer."""

from __future__ import annotations

from pathlib import Path

import numpy as np
from pymatgen.core import Lattice, Structure


def load_poscar(path: str | Path) -> Structure:
    """Load a POSCAR/CONTCAR as a pymatgen Structure.

    This intentionally avoids ``pymatgen.io.vasp`` because that package imports
    heavy output-parsing dependencies.
    """

    lines = [line.rstrip() for line in Path(path).read_text(encoding="utf-8").splitlines()]
    if len(lines) < 8:
        raise ValueError(f"POSCAR is too short: {path}")

    scale = float(lines[1].split()[0])
    if scale <= 0:
        raise ValueError("Only positive POSCAR scale factors are supported.")

    lattice = np.array(
        [[float(value) for value in lines[index].split()[:3]] for index in range(2, 5)],
        dtype=float,
    )
    lattice *= scale

    line5 = lines[5].split()
    try:
        counts = [int(value) for value in line5]
        species = [f"X{index + 1}" for index in range(len(counts))]
        coord_start = 7
    except ValueError:
        species = line5
        counts = [int(value) for value in lines[6].split()]
        coord_start = 8

    if len(species) != len(counts):
        raise ValueError("POSCAR species/count lines have different lengths.")

    if lines[coord_start - 1].strip().lower().startswith("s"):
        coord_start += 1

    coord_mode = lines[coord_start - 1].strip().lower()
    coords_are_cartesian = coord_mode.startswith(("c", "k"))
    if not coord_mode.startswith(("d", "c", "k")):
        raise ValueError(f"Unknown POSCAR coordinate mode: {lines[coord_start - 1]}")

    total_sites = sum(counts)
    coord_lines = lines[coord_start : coord_start + total_sites]
    if len(coord_lines) != total_sites:
        raise ValueError("POSCAR does not contain the expected number of coordinate lines.")

    expanded_species = []
    for symbol, count in zip(species, counts):
        expanded_species.extend([symbol] * count)

    coords = np.array(
        [[float(value) for value in line.split()[:3]] for line in coord_lines],
        dtype=float,
    )
    if coords_are_cartesian:
        coords *= scale

    return Structure(
        Lattice(lattice),
        expanded_species,
        coords,
        coords_are_cartesian=coords_are_cartesian,
    )


def write_poscar(structure: Structure, path: str | Path) -> None:
    """Write a POSCAR file."""

    species_order = []
    for site in structure:
        symbol = site.specie.symbol
        if symbol not in species_order:
            species_order.append(symbol)

    grouped_sites = []
    counts = []
    for symbol in species_order:
        sites = [site for site in structure if site.specie.symbol == symbol]
        grouped_sites.extend(sites)
        counts.append(len(sites))

    lines = [
        "generated by VaspTools",
        "1.0",
        *["  " + "  ".join(f"{value: .16f}" for value in row) for row in structure.lattice.matrix],
        "  " + "  ".join(species_order),
        "  " + "  ".join(str(count) for count in counts),
        "Direct",
    ]
    for site in grouped_sites:
        lines.append("  " + "  ".join(f"{value: .16f}" for value in site.frac_coords))

    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")
